//
// File generated by /opt/cern/root/bin/rootcint at Thu Nov 20 14:03:06 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dIhomedIschumansdIProjectsdIMultiDimdIsrcdIMultiDimDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "MultiDimDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TMultiDim_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TMultiDim(void *p = 0);
   static void *newArray_TMultiDim(Long_t size, void *p);
   static void delete_TMultiDim(void *p);
   static void deleteArray_TMultiDim(void *p);
   static void destruct_TMultiDim(void *p);
   static void streamer_TMultiDim(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TMultiDim*)
   {
      ::TMultiDim *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TMultiDim >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TMultiDim", ::TMultiDim::Class_Version(), "/home/schumans/Projects/MultiDim/src/TMultiDim.h", 30,
                  typeid(::TMultiDim), DefineBehavior(ptr, ptr),
                  &::TMultiDim::Dictionary, isa_proxy, 0,
                  sizeof(::TMultiDim) );
      instance.SetNew(&new_TMultiDim);
      instance.SetNewArray(&newArray_TMultiDim);
      instance.SetDelete(&delete_TMultiDim);
      instance.SetDeleteArray(&deleteArray_TMultiDim);
      instance.SetDestructor(&destruct_TMultiDim);
      instance.SetStreamerFunc(&streamer_TMultiDim);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TMultiDim*)
   {
      return GenerateInitInstanceLocal((::TMultiDim*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TMultiDim*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TMultiDim::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TMultiDim::Class_Name()
{
   return "TMultiDim";
}

//______________________________________________________________________________
const char *TMultiDim::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TMultiDim*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TMultiDim::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TMultiDim*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TMultiDim::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TMultiDim*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TMultiDim::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TMultiDim*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TMultiDim::Streamer(TBuffer &R__b)
{
   // Stream an object of class TMultiDim.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> fNDim;
      R__b >> fNValue;
      R__b >> fNCoord;
      delete [] fNBins;
      fNBins = new UInt_t[fNDim];
      R__b.ReadFastArray(fNBins,fNDim);
      delete [] fBin;
      fBin = new UInt_t[fNDim];
      R__b.ReadFastArray(fBin,fNDim);
      delete [] fValue;
      fValue = new Double_t[fNValue];
      R__b.ReadFastArray(fValue,fNValue);
      delete [] fCoord;
      fCoord = new Double_t[fNCoord];
      R__b.ReadFastArray(fCoord,fNCoord);
      delete [] fPoint;
      fPoint = new Double_t[fNDim];
      R__b.ReadFastArray(fPoint,fNDim);
      R__b.CheckByteCount(R__s, R__c, TMultiDim::IsA());
   } else {
      R__c = R__b.WriteVersion(TMultiDim::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << fNDim;
      R__b << fNValue;
      R__b << fNCoord;
      R__b.WriteFastArray(fNBins,fNDim);
      R__b.WriteFastArray(fBin,fNDim);
      R__b.WriteFastArray(fValue,fNValue);
      R__b.WriteFastArray(fCoord,fNCoord);
      R__b.WriteFastArray(fPoint,fNDim);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TMultiDim::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TMultiDim.
      TClass *R__cl = ::TMultiDim::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fNDim", &fNDim);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fNValue", &fNValue);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fNCoord", &fNCoord);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fNBins", &fNBins);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fBin", &fBin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fValue", &fValue);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCoord", &fCoord);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fPoint", &fPoint);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TMultiDim(void *p) {
      return  p ? new(p) ::TMultiDim : new ::TMultiDim;
   }
   static void *newArray_TMultiDim(Long_t nElements, void *p) {
      return p ? new(p) ::TMultiDim[nElements] : new ::TMultiDim[nElements];
   }
   // Wrapper around operator delete
   static void delete_TMultiDim(void *p) {
      delete ((::TMultiDim*)p);
   }
   static void deleteArray_TMultiDim(void *p) {
      delete [] ((::TMultiDim*)p);
   }
   static void destruct_TMultiDim(void *p) {
      typedef ::TMultiDim current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TMultiDim(TBuffer &buf, void *obj) {
      ((::TMultiDim*)obj)->::TMultiDim::Streamer(buf);
   }
} // end of namespace ROOT for class ::TMultiDim

/********************************************************
* /home/schumans/Projects/MultiDim/src/MultiDimDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableMultiDimDict();

extern "C" void G__set_cpp_environmentMultiDimDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/home/schumans/Projects/MultiDim/src/TMultiDim.h");
  G__cpp_reset_tagtableMultiDimDict();
}
#include <new>
extern "C" int G__cpp_dllrevMultiDimDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TMultiDim */
static int G__MultiDimDict_160_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TMultiDim* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TMultiDim[n];
     } else {
       p = new((void*) gvp) TMultiDim[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TMultiDim;
     } else {
       p = new((void*) gvp) TMultiDim;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__MultiDimDictLN_TMultiDim));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TMultiDim* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TMultiDim((UInt_t) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) TMultiDim((UInt_t) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__MultiDimDictLN_TMultiDim));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((TMultiDim*) G__getstructoffset())->GetNDim());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetNDim((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetNBins((UInt_t*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetNBins((UInt_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetNBins((UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetNBins((UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetNBins((UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetNBins((UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetNBins((UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4]), (UInt_t) G__int(libp->para[5]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetNBins(
(UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4]), (UInt_t) G__int(libp->para[5])
, (UInt_t) G__int(libp->para[6]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetNBins(
(UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4]), (UInt_t) G__int(libp->para[5])
, (UInt_t) G__int(libp->para[6]), (UInt_t) G__int(libp->para[7]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetNBins(
(UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4]), (UInt_t) G__int(libp->para[5])
, (UInt_t) G__int(libp->para[6]), (UInt_t) G__int(libp->para[7])
, (UInt_t) G__int(libp->para[8]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetNBins(
(UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4]), (UInt_t) G__int(libp->para[5])
, (UInt_t) G__int(libp->para[6]), (UInt_t) G__int(libp->para[7])
, (UInt_t) G__int(libp->para[8]), (UInt_t) G__int(libp->para[9]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((TMultiDim*) G__getstructoffset())->GetNBins((UInt_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetValue((UInt_t*) G__int(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetValue((UInt_t) G__int(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetValue((UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (Double_t) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetValue((UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (Double_t) G__double(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetValue((UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (Double_t) G__double(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetValue((UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4]), (Double_t) G__double(libp->para[5]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetValue(
(UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4]), (UInt_t) G__int(libp->para[5])
, (Double_t) G__double(libp->para[6]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetValue(
(UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4]), (UInt_t) G__int(libp->para[5])
, (UInt_t) G__int(libp->para[6]), (Double_t) G__double(libp->para[7]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetValue(
(UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4]), (UInt_t) G__int(libp->para[5])
, (UInt_t) G__int(libp->para[6]), (UInt_t) G__int(libp->para[7])
, (Double_t) G__double(libp->para[8]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetValue(
(UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4]), (UInt_t) G__int(libp->para[5])
, (UInt_t) G__int(libp->para[6]), (UInt_t) G__int(libp->para[7])
, (UInt_t) G__int(libp->para[8]), (Double_t) G__double(libp->para[9]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetValue(
(UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4]), (UInt_t) G__int(libp->para[5])
, (UInt_t) G__int(libp->para[6]), (UInt_t) G__int(libp->para[7])
, (UInt_t) G__int(libp->para[8]), (UInt_t) G__int(libp->para[9])
, (Double_t) G__double(libp->para[10]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->GetValue((UInt_t*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->GetValue((UInt_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->GetValue((UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->GetValue((UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->GetValue((UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->GetValue((UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->GetValue((UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4]), (UInt_t) G__int(libp->para[5])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->GetValue(
(UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4]), (UInt_t) G__int(libp->para[5])
, (UInt_t) G__int(libp->para[6])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->GetValue(
(UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4]), (UInt_t) G__int(libp->para[5])
, (UInt_t) G__int(libp->para[6]), (UInt_t) G__int(libp->para[7])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->GetValue(
(UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4]), (UInt_t) G__int(libp->para[5])
, (UInt_t) G__int(libp->para[6]), (UInt_t) G__int(libp->para[7])
, (UInt_t) G__int(libp->para[8])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->GetValue(
(UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (UInt_t) G__int(libp->para[3])
, (UInt_t) G__int(libp->para[4]), (UInt_t) G__int(libp->para[5])
, (UInt_t) G__int(libp->para[6]), (UInt_t) G__int(libp->para[7])
, (UInt_t) G__int(libp->para[8]), (UInt_t) G__int(libp->para[9])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetCoord((UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (Double_t) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->SetCoord((UInt_t) G__int(libp->para[0]), (Double_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->GetCoord((UInt_t) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->Interpolate((Double_t*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->Interpolate((Double_t) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->Interpolate((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->Interpolate((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->Interpolate((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->Interpolate((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->Interpolate((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]), (Double_t) G__double(libp->para[5])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->Interpolate(
(Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]), (Double_t) G__double(libp->para[5])
, (Double_t) G__double(libp->para[6])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->Interpolate(
(Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]), (Double_t) G__double(libp->para[5])
, (Double_t) G__double(libp->para[6]), (Double_t) G__double(libp->para[7])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->Interpolate(
(Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]), (Double_t) G__double(libp->para[5])
, (Double_t) G__double(libp->para[6]), (Double_t) G__double(libp->para[7])
, (Double_t) G__double(libp->para[8])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TMultiDim*) G__getstructoffset())->Interpolate(
(Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]), (Double_t) G__double(libp->para[5])
, (Double_t) G__double(libp->para[6]), (Double_t) G__double(libp->para[7])
, (Double_t) G__double(libp->para[8]), (Double_t) G__double(libp->para[9])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TMultiDim::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_57(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TMultiDim::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_58(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TMultiDim::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_59(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TMultiDim::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_63(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMultiDim*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_64(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TMultiDim::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_65(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TMultiDim::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_66(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TMultiDim::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MultiDimDict_160_0_67(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TMultiDim::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__MultiDimDict_160_0_68(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TMultiDim* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TMultiDim(*(TMultiDim*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__MultiDimDictLN_TMultiDim));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TMultiDim G__TTMultiDim;
static int G__MultiDimDict_160_0_69(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TMultiDim*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TMultiDim*) (soff+(sizeof(TMultiDim)*i)))->~G__TTMultiDim();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TMultiDim*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TMultiDim*) (soff))->~G__TTMultiDim();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__MultiDimDict_160_0_70(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TMultiDim* dest = (TMultiDim*) G__getstructoffset();
   *dest = *(TMultiDim*) libp->para[0].ref;
   const TMultiDim& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TMultiDim */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncMultiDimDict {
 public:
  G__Sizep2memfuncMultiDimDict(): p(&G__Sizep2memfuncMultiDimDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncMultiDimDict::*p)();
};

size_t G__get_sizep2memfuncMultiDimDict()
{
  G__Sizep2memfuncMultiDimDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceMultiDimDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__MultiDimDictLN_TMultiDim))) {
     TMultiDim *G__Lderived;
     G__Lderived=(TMultiDim*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__MultiDimDictLN_TMultiDim),G__get_linked_tagnum(&G__MultiDimDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableMultiDimDict() {

   /* Setting up typedef entry */
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__MultiDimDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MultiDimDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MultiDimDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MultiDimDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MultiDimDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__MultiDimDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MultiDimDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MultiDimDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MultiDimDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MultiDimDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TMultiDim */
static void G__setup_memvarTMultiDim(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__MultiDimDictLN_TMultiDim));
   { TMultiDim *p; p=(TMultiDim*)0x1000; if (p) { }
   G__memvar_setup((void*)0,104,0,0,-1,G__defined_typename("UInt_t"),-1,4,"fNDim=",0,"Number of dimensions of parameter space");
   G__memvar_setup((void*)0,104,0,0,-1,G__defined_typename("UInt_t"),-1,4,"fNValue=",0,"Total number of data points in n-dim. parameter space");
   G__memvar_setup((void*)0,104,0,0,-1,G__defined_typename("UInt_t"),-1,4,"fNCoord=",0,"Total number of coordinate positions of n-dim. parameter space");
   G__memvar_setup((void*)0,72,0,0,-1,G__defined_typename("UInt_t"),-1,4,"fNBins=",0,"[fNDim]:   Array (=vector) for number of bins in each dimension");
   G__memvar_setup((void*)0,72,0,0,-1,G__defined_typename("UInt_t"),-1,4,"fBin=",0,"[fNDim]:   Array (=vector) for current bin positions in each dimension");
   G__memvar_setup((void*)0,68,0,0,-1,G__defined_typename("Double_t"),-1,4,"fValue=",0,"[fNValue]: (Flattened) array of data values for each point in n-dim. parameter space");
   G__memvar_setup((void*)0,68,0,0,-1,G__defined_typename("Double_t"),-1,4,"fCoord=",0,"[fNCoord]: Array for coordinate positions of n-dim. parameter space");
   G__memvar_setup((void*)0,68,0,0,-1,G__defined_typename("Double_t"),-1,4,"fPoint=",0,"[fNDim]:   Array (=vector) for point in n-dim. parameter space for which to interpolate");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__MultiDimDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarMultiDimDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTMultiDim(void) {
   /* TMultiDim */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__MultiDimDictLN_TMultiDim));
   G__memfunc_setup("GetValueIdx",1090,(G__InterfaceMethod) NULL, 104, -1, G__defined_typename("UInt_t"), 0, 0, 1, 4, 0, "", "Calculates flattened 1-dim. array index from n-dim. bin position vector", (void*) NULL, 0);
   G__memfunc_setup("GetCoordIdx",1084,(G__InterfaceMethod) NULL, 104, -1, G__defined_typename("UInt_t"), 0, 2, 1, 4, 0, 
"h - 'UInt_t' 0 - dim h - 'UInt_t' 0 - bin", "Calculates index in coordinate array for given dimension and bin position", (void*) NULL, 0);
   G__memfunc_setup("AllocMem",778,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", "Reserves memory for current settings of dimensions and binning ", (void*) NULL, 0);
   G__memfunc_setup("TMultiDim",889,G__MultiDimDict_160_0_4, 105, G__get_linked_tagnum(&G__MultiDimDictLN_TMultiDim), -1, 0, 0, 1, 1, 0, "", "Default c'tor", (void*) NULL, 0);
   G__memfunc_setup("TMultiDim",889,G__MultiDimDict_160_0_5, 105, G__get_linked_tagnum(&G__MultiDimDictLN_TMultiDim), -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - ndim", "C'tor with dimension setting", (void*) NULL, 0);
   G__memfunc_setup("GetNDim",648,G__MultiDimDict_160_0_6, 104, -1, G__defined_typename("UInt_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetNDim",660,G__MultiDimDict_160_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - ndim", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetNBins",774,G__MultiDimDict_160_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "H - 'UInt_t' 0 - n", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetNBins",774,G__MultiDimDict_160_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - n0", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetNBins",774,G__MultiDimDict_160_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetNBins",774,G__MultiDimDict_160_0_11, 121, -1, -1, 0, 3, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetNBins",774,G__MultiDimDict_160_0_12, 121, -1, -1, 0, 4, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetNBins",774,G__MultiDimDict_160_0_13, 121, -1, -1, 0, 5, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3 "
"h - 'UInt_t' 0 - n4", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetNBins",774,G__MultiDimDict_160_0_14, 121, -1, -1, 0, 6, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3 "
"h - 'UInt_t' 0 - n4 h - 'UInt_t' 0 - n5", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetNBins",774,G__MultiDimDict_160_0_15, 121, -1, -1, 0, 7, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3 "
"h - 'UInt_t' 0 - n4 h - 'UInt_t' 0 - n5 "
"h - 'UInt_t' 0 - n6", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetNBins",774,G__MultiDimDict_160_0_16, 121, -1, -1, 0, 8, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3 "
"h - 'UInt_t' 0 - n4 h - 'UInt_t' 0 - n5 "
"h - 'UInt_t' 0 - n6 h - 'UInt_t' 0 - n7", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetNBins",774,G__MultiDimDict_160_0_17, 121, -1, -1, 0, 9, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3 "
"h - 'UInt_t' 0 - n4 h - 'UInt_t' 0 - n5 "
"h - 'UInt_t' 0 - n6 h - 'UInt_t' 0 - n7 "
"h - 'UInt_t' 0 - n8", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetNBins",774,G__MultiDimDict_160_0_18, 121, -1, -1, 0, 10, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3 "
"h - 'UInt_t' 0 - n4 h - 'UInt_t' 0 - n5 "
"h - 'UInt_t' 0 - n6 h - 'UInt_t' 0 - n7 "
"h - 'UInt_t' 0 - n8 h - 'UInt_t' 0 - n9", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetNBins",762,G__MultiDimDict_160_0_19, 104, -1, G__defined_typename("UInt_t"), 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - dim", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetValue",809,G__MultiDimDict_160_0_20, 121, -1, -1, 0, 2, 1, 1, 0, 
"H - 'UInt_t' 0 - n d - 'Double_t' 0 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetValue",809,G__MultiDimDict_160_0_21, 121, -1, -1, 0, 2, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 d - 'Double_t' 0 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetValue",809,G__MultiDimDict_160_0_22, 121, -1, -1, 0, 3, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"d - 'Double_t' 0 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetValue",809,G__MultiDimDict_160_0_23, 121, -1, -1, 0, 4, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 d - 'Double_t' 0 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetValue",809,G__MultiDimDict_160_0_24, 121, -1, -1, 0, 5, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3 "
"d - 'Double_t' 0 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetValue",809,G__MultiDimDict_160_0_25, 121, -1, -1, 0, 6, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3 "
"h - 'UInt_t' 0 - n4 d - 'Double_t' 0 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetValue",809,G__MultiDimDict_160_0_26, 121, -1, -1, 0, 7, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3 "
"h - 'UInt_t' 0 - n4 h - 'UInt_t' 0 - n5 "
"d - 'Double_t' 0 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetValue",809,G__MultiDimDict_160_0_27, 121, -1, -1, 0, 8, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3 "
"h - 'UInt_t' 0 - n4 h - 'UInt_t' 0 - n5 "
"h - 'UInt_t' 0 - n6 d - 'Double_t' 0 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetValue",809,G__MultiDimDict_160_0_28, 121, -1, -1, 0, 9, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3 "
"h - 'UInt_t' 0 - n4 h - 'UInt_t' 0 - n5 "
"h - 'UInt_t' 0 - n6 h - 'UInt_t' 0 - n7 "
"d - 'Double_t' 0 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetValue",809,G__MultiDimDict_160_0_29, 121, -1, -1, 0, 10, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3 "
"h - 'UInt_t' 0 - n4 h - 'UInt_t' 0 - n5 "
"h - 'UInt_t' 0 - n6 h - 'UInt_t' 0 - n7 "
"h - 'UInt_t' 0 - n8 d - 'Double_t' 0 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetValue",809,G__MultiDimDict_160_0_30, 121, -1, -1, 0, 11, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3 "
"h - 'UInt_t' 0 - n4 h - 'UInt_t' 0 - n5 "
"h - 'UInt_t' 0 - n6 h - 'UInt_t' 0 - n7 "
"h - 'UInt_t' 0 - n8 h - 'UInt_t' 0 - n9 "
"d - 'Double_t' 0 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetValue",797,G__MultiDimDict_160_0_31, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "H - 'UInt_t' 0 - n", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetValue",797,G__MultiDimDict_160_0_32, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "h - 'UInt_t' 0 - n0", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetValue",797,G__MultiDimDict_160_0_33, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetValue",797,G__MultiDimDict_160_0_34, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetValue",797,G__MultiDimDict_160_0_35, 100, -1, G__defined_typename("Double_t"), 0, 4, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetValue",797,G__MultiDimDict_160_0_36, 100, -1, G__defined_typename("Double_t"), 0, 5, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3 "
"h - 'UInt_t' 0 - n4", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetValue",797,G__MultiDimDict_160_0_37, 100, -1, G__defined_typename("Double_t"), 0, 6, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3 "
"h - 'UInt_t' 0 - n4 h - 'UInt_t' 0 - n5", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetValue",797,G__MultiDimDict_160_0_38, 100, -1, G__defined_typename("Double_t"), 0, 7, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3 "
"h - 'UInt_t' 0 - n4 h - 'UInt_t' 0 - n5 "
"h - 'UInt_t' 0 - n6", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetValue",797,G__MultiDimDict_160_0_39, 100, -1, G__defined_typename("Double_t"), 0, 8, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3 "
"h - 'UInt_t' 0 - n4 h - 'UInt_t' 0 - n5 "
"h - 'UInt_t' 0 - n6 h - 'UInt_t' 0 - n7", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetValue",797,G__MultiDimDict_160_0_40, 100, -1, G__defined_typename("Double_t"), 0, 9, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3 "
"h - 'UInt_t' 0 - n4 h - 'UInt_t' 0 - n5 "
"h - 'UInt_t' 0 - n6 h - 'UInt_t' 0 - n7 "
"h - 'UInt_t' 0 - n8", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetValue",797,G__MultiDimDict_160_0_41, 100, -1, G__defined_typename("Double_t"), 0, 10, 1, 1, 0, 
"h - 'UInt_t' 0 - n0 h - 'UInt_t' 0 - n1 "
"h - 'UInt_t' 0 - n2 h - 'UInt_t' 0 - n3 "
"h - 'UInt_t' 0 - n4 h - 'UInt_t' 0 - n5 "
"h - 'UInt_t' 0 - n6 h - 'UInt_t' 0 - n7 "
"h - 'UInt_t' 0 - n8 h - 'UInt_t' 0 - n9", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetCoord",803,G__MultiDimDict_160_0_42, 121, -1, -1, 0, 3, 1, 1, 0, 
"h - 'UInt_t' 0 - dim h - 'UInt_t' 0 - bin "
"d - 'Double_t' 0 - coord", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetCoord",803,G__MultiDimDict_160_0_43, 121, -1, -1, 0, 2, 1, 1, 0, 
"h - 'UInt_t' 0 - dim D - 'Double_t' 0 - coord", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetCoord",791,G__MultiDimDict_160_0_44, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"h - 'UInt_t' 0 - dim h - 'UInt_t' 0 - bin", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Interpolate",1159,G__MultiDimDict_160_0_45, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "D - 'Double_t' 0 - x", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Interpolate",1159,G__MultiDimDict_160_0_46, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "d - 'Double_t' 0 - x0", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Interpolate",1159,G__MultiDimDict_160_0_47, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 - x0 d - 'Double_t' 0 - x1", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Interpolate",1159,G__MultiDimDict_160_0_48, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"d - 'Double_t' 0 - x0 d - 'Double_t' 0 - x1 "
"d - 'Double_t' 0 - x2", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Interpolate",1159,G__MultiDimDict_160_0_49, 100, -1, G__defined_typename("Double_t"), 0, 4, 1, 1, 0, 
"d - 'Double_t' 0 - x0 d - 'Double_t' 0 - x1 "
"d - 'Double_t' 0 - x2 d - 'Double_t' 0 - x3", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Interpolate",1159,G__MultiDimDict_160_0_50, 100, -1, G__defined_typename("Double_t"), 0, 5, 1, 1, 0, 
"d - 'Double_t' 0 - x0 d - 'Double_t' 0 - x1 "
"d - 'Double_t' 0 - x2 d - 'Double_t' 0 - x3 "
"d - 'Double_t' 0 - x4", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Interpolate",1159,G__MultiDimDict_160_0_51, 100, -1, G__defined_typename("Double_t"), 0, 6, 1, 1, 0, 
"d - 'Double_t' 0 - x0 d - 'Double_t' 0 - x1 "
"d - 'Double_t' 0 - x2 d - 'Double_t' 0 - x3 "
"d - 'Double_t' 0 - x4 d - 'Double_t' 0 - x5", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Interpolate",1159,G__MultiDimDict_160_0_52, 100, -1, G__defined_typename("Double_t"), 0, 7, 1, 1, 0, 
"d - 'Double_t' 0 - x0 d - 'Double_t' 0 - x1 "
"d - 'Double_t' 0 - x2 d - 'Double_t' 0 - x3 "
"d - 'Double_t' 0 - x4 d - 'Double_t' 0 - x5 "
"d - 'Double_t' 0 - x6", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Interpolate",1159,G__MultiDimDict_160_0_53, 100, -1, G__defined_typename("Double_t"), 0, 8, 1, 1, 0, 
"d - 'Double_t' 0 - x0 d - 'Double_t' 0 - x1 "
"d - 'Double_t' 0 - x2 d - 'Double_t' 0 - x3 "
"d - 'Double_t' 0 - x4 d - 'Double_t' 0 - x5 "
"d - 'Double_t' 0 - x6 d - 'Double_t' 0 - x7", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Interpolate",1159,G__MultiDimDict_160_0_54, 100, -1, G__defined_typename("Double_t"), 0, 9, 1, 1, 0, 
"d - 'Double_t' 0 - x0 d - 'Double_t' 0 - x1 "
"d - 'Double_t' 0 - x2 d - 'Double_t' 0 - x3 "
"d - 'Double_t' 0 - x4 d - 'Double_t' 0 - x5 "
"d - 'Double_t' 0 - x6 d - 'Double_t' 0 - x7 "
"d - 'Double_t' 0 - x8", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Interpolate",1159,G__MultiDimDict_160_0_55, 100, -1, G__defined_typename("Double_t"), 0, 10, 1, 1, 0, 
"d - 'Double_t' 0 - x0 d - 'Double_t' 0 - x1 "
"d - 'Double_t' 0 - x2 d - 'Double_t' 0 - x3 "
"d - 'Double_t' 0 - x4 d - 'Double_t' 0 - x5 "
"d - 'Double_t' 0 - x6 d - 'Double_t' 0 - x7 "
"d - 'Double_t' 0 - x8 d - 'Double_t' 0 - x9", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__MultiDimDict_160_0_56, 85, G__get_linked_tagnum(&G__MultiDimDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TMultiDim::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__MultiDimDict_160_0_57, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TMultiDim::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__MultiDimDict_160_0_58, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TMultiDim::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__MultiDimDict_160_0_59, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TMultiDim::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__MultiDimDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__MultiDimDict_160_0_63, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__MultiDimDict_160_0_64, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TMultiDim::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__MultiDimDict_160_0_65, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TMultiDim::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__MultiDimDict_160_0_66, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TMultiDim::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__MultiDimDict_160_0_67, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TMultiDim::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TMultiDim", 889, G__MultiDimDict_160_0_68, (int) ('i'), G__get_linked_tagnum(&G__MultiDimDictLN_TMultiDim), -1, 0, 1, 1, 1, 0, "u 'TMultiDim' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TMultiDim", 1015, G__MultiDimDict_160_0_69, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__MultiDimDict_160_0_70, (int) ('u'), G__get_linked_tagnum(&G__MultiDimDictLN_TMultiDim), -1, 1, 1, 1, 1, 0, "u 'TMultiDim' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncMultiDimDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalMultiDimDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcMultiDimDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__MultiDimDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__MultiDimDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__MultiDimDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__MultiDimDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__MultiDimDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__MultiDimDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__MultiDimDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__MultiDimDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__MultiDimDictLN_TMultiDim = { "TMultiDim" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableMultiDimDict() {
  G__MultiDimDictLN_TClass.tagnum = -1 ;
  G__MultiDimDictLN_TBuffer.tagnum = -1 ;
  G__MultiDimDictLN_TMemberInspector.tagnum = -1 ;
  G__MultiDimDictLN_TObject.tagnum = -1 ;
  G__MultiDimDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__MultiDimDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MultiDimDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__MultiDimDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MultiDimDictLN_TMultiDim.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableMultiDimDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__MultiDimDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__MultiDimDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__MultiDimDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__MultiDimDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__MultiDimDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__MultiDimDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__MultiDimDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__MultiDimDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__MultiDimDictLN_TMultiDim),sizeof(TMultiDim),-1,62720,(char*)NULL,G__setup_memvarTMultiDim,G__setup_memfuncTMultiDim);
}
extern "C" void G__cpp_setupMultiDimDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupMultiDimDict()");
  G__set_cpp_environmentMultiDimDict();
  G__cpp_setup_tagtableMultiDimDict();

  G__cpp_setup_inheritanceMultiDimDict();

  G__cpp_setup_typetableMultiDimDict();

  G__cpp_setup_memvarMultiDimDict();

  G__cpp_setup_memfuncMultiDimDict();
  G__cpp_setup_globalMultiDimDict();
  G__cpp_setup_funcMultiDimDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncMultiDimDict();
  return;
}
class G__cpp_setup_initMultiDimDict {
  public:
    G__cpp_setup_initMultiDimDict() { G__add_setup_func("MultiDimDict",(G__incsetup)(&G__cpp_setupMultiDimDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initMultiDimDict() { G__remove_setup_func("MultiDimDict"); }
};
G__cpp_setup_initMultiDimDict G__cpp_setup_initializerMultiDimDict;

