/********************************************************************
* /home/schumans/Projects/MultiDim/src/MultiDimDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/schumans/Projects/MultiDim/src/MultiDimDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMultiDimDict();
extern void G__cpp_setup_inheritanceMultiDimDict();
extern void G__cpp_setup_typetableMultiDimDict();
extern void G__cpp_setup_memvarMultiDimDict();
extern void G__cpp_setup_globalMultiDimDict();
extern void G__cpp_setup_memfuncMultiDimDict();
extern void G__cpp_setup_funcMultiDimDict();
extern void G__set_cpp_environmentMultiDimDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/schumans/Projects/MultiDim/src/TMultiDim.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MultiDimDictLN_TClass;
extern G__linked_taginfo G__MultiDimDictLN_TBuffer;
extern G__linked_taginfo G__MultiDimDictLN_TMemberInspector;
extern G__linked_taginfo G__MultiDimDictLN_TObject;
extern G__linked_taginfo G__MultiDimDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MultiDimDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MultiDimDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MultiDimDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MultiDimDictLN_TMultiDim;

/* STUB derived class for protected member access */
